DROP TABLE IF EXISTS ddos;

CREATE TABLE
IF NOT EXISTS ddos (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    start_time TEXT NOT NULL, 
    end_time TEXT NOT NULL, 
    n INTEGER NOT NULL
);

